// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1s5wVVb7g7OjoRcJQPuGdzZ6LDS4CmoQ',
    appId: '1:138107844519:web:c51c142f9ab62783abe882',
    messagingSenderId: '138107844519',
    projectId: 'swapme-72da1',
    authDomain: 'swapme-72da1.firebaseapp.com',
    storageBucket: 'swapme-72da1.firebasestorage.app',
    measurementId: 'G-K60C2RTN48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEw5u6c5WX6zl6-SsfGE9Xt7nISkgSN9E',
    appId: '1:138107844519:android:20ef7c8eb5c60fa1abe882',
    messagingSenderId: '138107844519',
    projectId: 'swapme-72da1',
    storageBucket: 'swapme-72da1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdiUuHJyXe-1F7ArUVknj5zfNzrYPBX0o',
    appId: '1:138107844519:ios:9b5c0e51e6941d7dabe882',
    messagingSenderId: '138107844519',
    projectId: 'swapme-72da1',
    storageBucket: 'swapme-72da1.firebasestorage.app',
    androidClientId: '138107844519-25m1qvtoj1dcje6g9ja7gnddvtpjq6jj.apps.googleusercontent.com',
    iosClientId: '138107844519-2mrj6rtdrh01n84j5ct6tl7rohr4ka7h.apps.googleusercontent.com',
    iosBundleId: 'com.swapapp.me',
  );
}
